# Homepage Services Configuration
# Icons from: https://github.com/walkxcode/dashboard-icons

- Media Management:
    - Sonarr:
        icon: sonarr.png
        href: http://192.169.50.59:8989
        description: TV Show Management
        widget:
          type: sonarr
          url: http://192.168.50.59:8989
          key: 12c3cf446b4f4cb7aa77d796b653f8c9

    - Radarr:
        icon: radarr.png
        href: http://192.169.50.59:7878
        description: Movie Management
        widget:
          type: radarr
          url: http://192.168.50.59:7878
          key: 91c421d1238d402b8eeb9f083107205a

    - Bazarr:
        icon: bazarr.png
        href: http://192.169.50.59:6767
        description: Subtitle Management
        widget:
          type: bazarr
          url: http://192.168.50.59:6767
          key: 07b3286400830ae2fffc82e91e733cfb

    - Prowlarr:
        icon: prowlarr.png
        href: http://192.169.50.59:9696
        description: Indexer Management
        widget:
          type: prowlarr
          url: http://192.168.50.59:9696
          key: 35ccdc07d49347188b462d2af114cc5e

- Download Clients:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.169.50.59:8085
        description: BitTorrent Client
        widget:
          type: qbittorrent
          url: http://192.168.50.59:8080
          username: admin
          password: dose.caution.Blow.2 # Change this!

- Media Processing:
    - Unpackerr:
        icon: https://raw.githubusercontent.com/Unpackerr/unpackerr/main/init/windows/Unpackerr.png
        href: #
        description: Automatic Extraction
        ping: 192.168.50.59

    - qBitManage:
        icon: qbittorrent.png
        href: #
        description: Torrent Management
        ping: 192.168.50.59
