# Homepage Services Configuration
# Icons from: https://github.com/walkxcode/dashboard-icons

- Media Management:
    - Sonarr:
        icon: sonarr.png
        href: http://192.169.50.59:8989
        description: TV Show Management
        widget:
          type: sonarr
          url: http://192.168.50.59:8989
          key: 12c3cf446b4f4cb7aa77d796b653f8c9

    - Radarr:
        icon: radarr.png
        href: http://192.169.50.59:7878
        description: Movie Management
        widget:
          type: radarr
          url: http://192.168.50.59:7878
          key: 91c421d1238d402b8eeb9f083107205a

    - Bazarr:
        icon: bazarr.png
        href: http://192.169.50.59:6767
        description: Subtitle Management
        widget:
          type: bazarr
          url: http://192.168.50.59:6767
          key: 07b3286400830ae2fffc82e91e733cfb

    - Prowlarr:
        icon: prowlarr.png
        href: http://192.169.50.59:9696
        description: Indexer Management
        widget:
          type: prowlarr
          url: http://192.168.50.59:9696
          key: 35ccdc07d49347188b462d2af114cc5e

    - LazyLibrarian:
        icon: lazylibrarian.png
        href: http://192.169.50.59:5299
        description: Book & Audiobook Management

- Download Clients:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.169.50.59:8085
        description: BitTorrent Client
        widget:
          type: qbittorrent
          url: http://192.168.50.59:8080
          username: admin
          password: dose.caution.Blow.2 # Change this!

    - SABnzbd:
        icon: sabnzbd.png
        href: http://192.169.50.59:8082
        description: Usenet Client
        widget:
          type: sabnzbd
          url: http://192.168.50.59:8082
          key: # Add your API key here

    - slskd:
        icon: slskd.png
        href: http://192.169.50.59:5030
        description: Soulseek Client

- Media Servers:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.169.50.59:8096
        description: Media Server
        widget:
          type: jellyfin
          url: http://192.168.50.59:8096
          key: # Add your API key here
          enableBlocks: true
          enableNowPlaying: true

    - Jellyseerr:
        icon: jellyseerr.png
        href: http://192.169.50.59:5055
        description: Media Request Management
        widget:
          type: jellyseerr
          url: http://192.168.50.59:5055
          key: # Add your API key here

- Media Processing:
    - Tdarr:
        icon: tdarr.png
        href: http://192.169.50.59:8265
        description: Media Transcoding
        widget:
          type: tdarr
          url: http://192.168.50.59:8265

    - Beets:
        icon: https://raw.githubusercontent.com/beetbox/beets/master/docs/_static/beets_logo_128.png
        href: http://192.169.50.59:8337
        description: Music Organization

    - Unpackerr:
        icon: https://raw.githubusercontent.com/Unpackerr/unpackerr/main/init/windows/Unpackerr.png
        href: #
        description: Automatic Extraction
        ping: 192.168.50.59

    - qBitManage:
        icon: qbittorrent.png
        href: #
        description: Torrent Management
        ping: 192.168.50.59
